homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml
  
system_health:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret hass_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor: !include sensor.yml

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


# Configurator
panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url
    
# Zwave
zwave:
  usb_path: !secret zwave_usb_path
  polling_interval: 80000
  device_config: !include zwave_device_config.yaml
      
# Lovelace
lovelace:
  mode: yaml
  
media_player:
 - platform: plex
# Camera
camera:
  - platform: generic
    still_image_url: !secret radar_url
    name: Radar TX AUS
    

# Google Assistant
google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config:
    fan.ge_14287_fan_control_switch_level:
      name: Living Room Fan Speed Control
      expose: true
      room: Living Room
    light.ge_14294_inwall_smart_dimmer_level:
      name: Living Room Fan Light
      expose: true
      room: Living Room
    fan.ge_14287_fan_control_switch_level_2:
      name: Bedroom Fan Speed Control
      expose: true
      room: Bedroom
    light.ge_14294_inwall_smart_dimmer_level_2:
      name: Bedroom Fan Light
      expose: true
      room: Bedroom
    light.ge_14294_inwall_smart_dimmer_level_4:
      name: Kitchen Lights
      expose: true
      room: Kitchen
    light.ge_14294_inwall_smart_dimmer_level_3:
      name: Dining Room Lights
      expose: true
      room: Dining Room
    switch.ge_14291_inwall_smart_switch_switch_2:
      name: Front Hallway Light
      expose: true
      room: Hallway
    switch.ge_14291_inwall_smart_switch_switch:
      name: Front Exterior Lights
      expose: true
      room: Front Exterior
    
